=== TEAM-1-Surface-Air-Missile-System-Team/MissileSimulator/bin/NOM.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- NOM schema version
     # Revision History
	- 1.01 : 복합타입의 encoding 방식을 정의할 수 있는 encodingType 필드 추가.
	- 1.02 : 2024-07-11 nameNotes, semantics 일관성 적용.
	- 1.03 : 2024-07-16 name, nameNotes에 정규표현식 적용. 
	- 1.04 : 2024-07-19 name에 하이픈 추가.
	- 1.05 : 2024-11-29 하위 호환성 (XSD 1.01, NOMParser v1.7.3) 추가: attribute, parameter 이름에 '.' 허용.  nameNotes, note를 comments 용도로 복원
    - 1.06 : 2025-01-13 enumerationType에 optional attribute "endian" 추가
	- 1.07 : 2025-03-13 object/attribute, interaction/parameter, ComplexType/fieldType 내 indicatorMultiple, bits attribute 추가(누락부분 복원)
-->
<xs:schema xmlns:nom="lignex1.sw.nframework.NOM" elementFormDefault="qualified" targetNamespace="lignex1.sw.nframework.NOM"
	id="NOM" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Nex1ObjectModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="objects" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="object">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="attribute">
											<xs:complexType>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ .-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="size" type="xs:nonNegativeInteger" use="optional" />
												<xs:attribute name="fixedLength" type="xs:integer" use="optional" />
												<xs:attribute name="nameNotes" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="semantics" type="xs:string" use="optional" />
												<xs:attribute name="dataType" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="indicatorLength" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="indicatorMultiple" type="xs:integer" use="optional" />
												<xs:attribute name="bits" type="xs:nonNegativeInteger" use="optional" />
												<xs:attribute name="LSB" type="xs:decimal" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_.-])*" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="(0X|0x)[0-9a-fA-F]+|0[0-9]+|[0-9]+" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="nameNotes" use="optional" >
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="semantics" type="xs:string" use="optional" />
									<xs:attribute name="sharing" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="Publish|Subscribe|PublishSubscribe|Neither" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="orderType" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="TimeStamp|Receive" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="alignment" type="xs:boolean" use="optional" />
									<xs:attribute name="period" type="xs:integer" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="interactions" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="interaction">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="parameter">
											<xs:complexType>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ .-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="size" type="xs:nonNegativeInteger" use="optional" />
												<xs:attribute name="fixedLength" type="xs:integer" use="optional" />
												<xs:attribute name="nameNotes" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="semantics" type="xs:string" use="optional" />
												<xs:attribute name="dataType" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="indicatorLength" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="indicatorMultiple" type="xs:integer" use="optional" />
												<xs:attribute name="bits" type="xs:nonNegativeInteger" use="optional" />
												<xs:attribute name="LSB" type="xs:decimal" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_.-])*" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="id" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="(0X|0x)[0-9a-fA-F]+|0[0-9]+|[0-9]+" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="nameNotes" use="optional" >
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="semantics" type="xs:string" use="optional" />
									<xs:attribute name="sharing" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="Publish|Subscribe|PublishSubscribe|Neither" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="orderType" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="TimeStamp|Receive" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="alignment" type="xs:boolean" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="dataTypes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="basicTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="basicType">
											<xs:annotation>
												<xs:documentation>size는 bit가 아닌 byte의 size를 입력해야 합니다. endian은 big, little, none 중에 하나를 입력해야 합니다. signed는 unsigned일 경우에 false를 입력하며 signed일 경우는 이 attribute를 생략해도 됩니다.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="length" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="endian" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="little|big|none" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="signed" type="xs:boolean" />
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="Bool|Byte|Char|Short|Integer|Integer64|Float|Double|String|Variable|FixedString|FixedDatum" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="nameNotes" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<!--<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="semantics" type="xs:string" use="optional" />
												<xs:attribute name="note" type="xs:string" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="enumerationTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="enumerationType">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="0" maxOccurs="unbounded" name="enumerator">
														<xs:complexType>
															<xs:attribute name="name" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="value" type="xs:integer" use="required" />
															<xs:attribute name="nameNotes" use="optional" >
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<!--<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="semantics" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="length" use="optional">
													<xs:simpleType>
														<xs:restriction base="xs:integer">
															<xs:pattern value="1|2|4" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="nameNotes" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="semantics" type="xs:string" use="optional" />
												<xs:attribute name="endian" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="big" />
															<xs:enumeration value="little" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="complexTypes">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" maxOccurs="unbounded" name="complexType">
											<xs:complexType>
												<xs:sequence>
													<xs:element minOccurs="0" maxOccurs="unbounded" name="fieldType">
														<xs:complexType>
															<xs:attribute name="name" use="required" >
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ .-])*" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="nameNotes" use="optional" >
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="semantics" type="xs:string" use="optional" />
															<xs:attribute name="size" type="xs:nonNegativeInteger" use="optional" />
															<xs:attribute name="fixedLength" type="xs:integer" use="optional" />
															<xs:attribute name="dataType" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="indicatorLength" use="optional" >
																<xs:simpleType>
																	<xs:restriction base="xs:integer">
																		<xs:pattern value="0|1|2|4|8|-1|-2|-4|-8" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="indicatorMultiple" type="xs:integer" use="optional" />
															<xs:attribute name="bits" type="xs:nonNegativeInteger" use="optional" />
															<xs:attribute name="LSB" type="xs:decimal" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="nameNotes" use="optional" >
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_ -])*" />-->
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="semantics" type="xs:string" use="optional" />
												<xs:attribute name="encodingType" type="xs:string" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="notes">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="note">
								<xs:complexType>
									<xs:attribute name="name"  use="required" >
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<!--1.05 <xs:pattern value="[a-zA-Z0-9_-]([a-zA-Z0-9_-])*" />-->
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="semantics" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]+.[0-9]+" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="date" type="xs:date" use="required" />
			<xs:attribute name="author" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== TEAM-1-Surface-Air-Missile-System-Team/MissileSimulator/bin/SchemaRegistryData.xml
<?xml version="1.0" encoding="UTF-8"?>
<NOM:Nex1ObjectModel xmlns:NOM="lignex1.sw.nframework.NOM" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="lignex1.sw.nframework.NOM NOM.xsd" version="0.1" name="CommandManager" date="2023-12-06" author="PGM3연구소.4팀 하재희">
	<NOM:dataTypes>

		<NOM:basicTypes>
			<NOM:basicType name="double" length="8" endian="little" type="Double" nameNotes="1 2" semantics="64bit double, little endian"/>
			<NOM:basicType name="doubleBE" length="8" endian="big" type="Double" semantics="64bit double, big endian"/>
			<NOM:basicType name="float" length="4" endian="little" type="Float" semantics="32bit float, little endian"/>
			<NOM:basicType name="floatBE" length="4" endian="big" type="Float" semantics="32bit float, big endian"/>
			<NOM:basicType name="int" length="4" endian="little" type="Integer" semantics="32bit integer, little endian"/>
			<NOM:basicType name="intBE" length="4" endian="big" type="Integer" semantics="32bit integer, big endian"/>
			<NOM:basicType name="uint64" length="8" endian="little" signed="false" type="Integer64" semantics="64bit integer, little endian"/>
			<NOM:basicType name="uint64BE" length="8" endian="big" signed="false" type="Integer64" semantics="64bit unsigned integer, big endian"/>
			<NOM:basicType name="uint" length="4" endian="little" signed="false" type="Integer" semantics="32bit integer, little endian"/>
			<NOM:basicType name="uintBE" length="4" endian="big" signed="false" type="Integer" semantics="32bit unsigned integer, big endian"/>
			<NOM:basicType name="short" length="2" endian="little" type="Short" semantics="16bit integer(short), little endian"/>
			<NOM:basicType name="shortBE" length="2" endian="big" type="Short" semantics="16bit integer(short), big endian"/>
			<NOM:basicType name="ushort" length="2" endian="little" signed="false" type="Short" semantics="16bit integer(short), little endian"/>
			<NOM:basicType name="ushortBE" length="2" endian="big" signed="false" type="Short" semantics="16bit unsigned integer(short), big endian"/>
			<NOM:basicType name="char" length="1" endian="none" type="Char" semantics="8bit char value"/>
			<NOM:basicType name="uchar" length="1" endian="none" signed="false" type="Char" semantics="8bit char value"/>
			<NOM:basicType name="byte" length="1" endian="none" signed="false" type="Byte" semantics="8bit byte value"/>
			<NOM:basicType name="boolean" length="1" endian="little" type="Bool" semantics="8bit value"/>
			<NOM:basicType name="string" length="0" endian="none" signed="false" type="String" semantics="String"/>
			<NOM:basicType name="stringBE" length="0" endian="big" signed="false" type="String" semantics="String, indicator big endian"/>
			<NOM:basicType name="var" length="0" endian="little" signed="false" type="Variable" semantics="Variable"/>
		</NOM:basicTypes>
		<NOM:enumerationTypes>

		</NOM:enumerationTypes>


		<NOM:complexTypes>
			<!-- 발사대 타입 -->
			<NOM:complexType name="MissileStatusStruct" semantics="탑재된 미사일 목록 (ID, 타입 포함)">
				<NOM:fieldType name="MissileID" dataType="ushortBE" semantics="유도탄 식별자"/>
				<NOM:fieldType name="MissileAvailabilityStatus" dataType="ushortBE" semantics="유도탄 가용 상태(0: 비가역, 1: 가역)"/>
				<NOM:fieldType name="MissileLunachStatus" dataType="ushortBE" semantics="유도탄 발사 상태(0: 대기, 1: 초읽기, 2: 이탈)"/>
			</NOM:complexType>

			<NOM:complexType name="LauncherStatusStruct" semantics="탑재된 미사일 목록 (ID, 타입 포함)">
				<NOM:fieldType name="LaunchID" dataType="ushortBE" semantics="유도탄 식별자"/>
				<NOM:fieldType name="LauncherAvailabillityStatus" dataType="ushortBE" semantics="유도탄 가용 상태(0: 비가역, 1: 가역)"/>
			</NOM:complexType>

			<NOM:complexType name="MissileStatus" semantics="유도탄 가용 상태">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="0: 비가역, 1: 가역"/>
			</NOM:complexType>

			<NOM:complexType name="MissileLunachStatus" semantics="유도탄 발사 절차 상태">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="0: 대기, 1: 초읽기, 2: 이탈"/>
			</NOM:complexType>

			<NOM:complexType name="LauncherAvailabillityStatus" semantics="유도탄 가용 상태">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="0: 비가역, 1: 가역"/>
			</NOM:complexType>

			<NOM:complexType name="MissileControlCommand" semantics="유도탄 제어 명령">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="0: 중단, 1: 발사"/>
			</NOM:complexType>

			<!-- 공중위협, 유도탄, 레이다 타입 -->
			<NOM:complexType name="FlyStateStruct" semantics="SAAM_CFCS_ICD의 메시지 헤더 구조">
				<NOM:fieldType name="Tgt_Lat" dataType="doubleBE" semantics="위도"/>
				<NOM:fieldType name="Tgt_Lon" dataType="doubleBE" semantics="경도"/>
				<NOM:fieldType name="Tgt_Alt" dataType="doubleBE" semantics="고도"/>

				<NOM:fieldType name="v0" dataType="doubleBE" semantics="초기속도"/>

				<NOM:fieldType name="ECEF_x" dataType="doubleBE" semantics="ECEF x좌표"/>
				<NOM:fieldType name="ECEF_y" dataType="doubleBE" semantics="ECEF y좌표"/>
				<NOM:fieldType name="ECEF_z" dataType="doubleBE" semantics="ECEF z좌표"/>

				<NOM:fieldType name="ECEF_velo_x" dataType="doubleBE" semantics="ECEF 속도(N)"/>
				<NOM:fieldType name="ECEF_velo_y" dataType="doubleBE" semantics="ECEF 속도(E)"/>
				<NOM:fieldType name="ECEF_velo_z" dataType="doubleBE" semantics="ECEF 속도(D)"/>

				<NOM:fieldType name="velo_x" dataType="doubleBE" semantics="NED좌표계 속도(N)"/>
				<NOM:fieldType name="velo_y" dataType="doubleBE" semantics="NED좌표계 속도(E)"/>
				<NOM:fieldType name="velo_z" dataType="doubleBE" semantics="NED좌표계 속도(D)"/>

				<NOM:fieldType name="roll_angle" dataType="doubleBE" semantics="roll 각"/>
				<NOM:fieldType name="yaw_angle" dataType="doubleBE" semantics="yaw 각"/>
				<NOM:fieldType name="pitch_angle" dataType="doubleBE" semantics="pitch 각"/>
				<NOM:fieldType name="max_time" dataType="doubleBE" semantics="최대 비행시간"/>
			</NOM:complexType>


			<NOM:complexType name="ThreatType" semantics="ThreatType">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="1: 탄도탄, 2: 항공기"/>
			</NOM:complexType>

			<!-- 공통 -->
			<NOM:complexType name="messageHeaderStruct" semantics="SAAM_CFCS_ICD의 메시지 헤더 구조">
				<NOM:fieldType name="MessageID" dataType="ushortBE"/>
				<NOM:fieldType name="MessageLength" dataType="ushortBE"/>
			</NOM:complexType>

			<NOM:complexType name="AckResult" semantics="ushortBE">
				<NOM:fieldType name="value" dataType="ushortBE" semantics="0: 성공, 1: 실패"/>
			</NOM:complexType>
		</NOM:complexTypes>


	</NOM:dataTypes>
	<NOM:notes>
		<NOM:note name="1" semantics="semantic"/>
		<NOM:note name="2" semantics="semantic"/>
	</NOM:notes>
</NOM:Nex1ObjectModel>
